#!/usr/bin/env python3
"""
make_models_md.py — regenerate INSTALL.md's model list from the targets.

Every target's `targets/<kind>/<id>/target.json` already says which model files
it loads (`presets` and `models`: the family, the tier and ComfyUI's folder)
and where each one comes from (`downloads`: a url, or null and a `source` that
says what to search for). This turns that into the Markdown table in INSTALL.md,
so the download list cannot drift from what the code actually asks ComfyUI to
load. Nothing here is typed by hand, and no URL is invented: a file with no
trustworthy download record is listed as having none.

    python tools/make_models_md.py             # rewrite the block in INSTALL.md
    python tools/make_models_md.py --check     # exit 1 if it is out of date
    python tools/make_models_md.py --stdout    # print the block, write nothing

The block lives between the markers below; everything outside them is left
alone. tests/test_docs.py runs --check.

Run it after changing any target's `models`, `presets` or `downloads`.

Stdlib only (no ComfyUI needed: this reads target.json, not your models folder).
"""
from __future__ import annotations

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import targets as TG                                              # noqa: E402
from targets import modelid                                       # noqa: E402

INSTALL = os.path.join(ROOT, "INSTALL.md")
BEGIN = "<!-- BEGIN MODELS (generated by tools/make_models_md.py — do not edit) -->"
END = "<!-- END MODELS -->"

# the two targets a first render needs: the default video target and the
# default image target (the one that draws the references)
MINIMUM = (TG.DEFAULT_VIDEO_TARGET, TG.DEFAULT_IMAGE_TARGET)


# ---------------------------------------------------------------------------
# collecting
# ---------------------------------------------------------------------------

def collect() -> list[dict]:
    """One record per model file every target names, in target order:

        {"family", "file", "folder", "url", "source", "size", "tier",
         "uses": [{"target", "param", "tier", "feature"}]}

    A file two targets load is one record naming both. `tier` is the strongest
    tier any target gives it (required > accelerator > optional)."""
    out: dict[tuple[str, str], dict] = {}
    for t in TG.list_targets():
        models = t.models
        named = t.named_files()
        # param order is target.json's (model, LoRAs, text encoder, VAEs…), so
        # a family's place in the doc follows how the target is put together
        for param, spec in models.items():
            for name in sorted(n for n, p in named.items() if p == param):
                dl = TG.download_for(t, name, spec.get("folder"))
                # download_for keeps only folder/url/source; `size` is optional
                # and read from the raw record (none carries one yet)
                base = name.replace("\\", "/").rsplit("/", 1)[-1]
                raw = t.downloads.get(base) or t.downloads.get(name) or {}
                size = str(raw.get("size") or "")
                tier = spec["tier"]
                feature = spec["feature"] or (f"{param} {TG.model_stem(name)}"
                                              if tier == "optional" else "")
                key = (spec["family"], name)
                rec = out.get(key)
                if rec is None:
                    rec = out[key] = {"family": spec["family"], "file": name,
                                      "folder": dl["folder"] or "", "url": dl["url"],
                                      "source": dl["source"], "size": size,
                                      "tier": tier, "uses": []}
                rec["uses"].append({"target": t.id, "param": param, "tier": tier,
                                    "feature": feature})
                if TG.TIERS.index(tier) < TG.TIERS.index(rec["tier"]):
                    rec["tier"] = tier
                rec["url"] = rec["url"] or dl["url"]
                rec["size"] = rec["size"] or size
    return list(out.values())


def families(records: list[dict]) -> list[tuple[str, list[dict]]]:
    """[(family id, its records)], families in the order they first appear and
    files inside one sorted strongest tier first, then by name."""
    order: list[str] = []
    by_family: dict[str, list[dict]] = {}
    for r in records:
        if r["family"] not in by_family:
            by_family[r["family"]] = []
            order.append(r["family"])
        by_family[r["family"]].append(r)
    return [(f, sorted(by_family[f], key=lambda r: (TG.TIERS.index(r["tier"]), r["file"])))
            for f in order]


# ---------------------------------------------------------------------------
# rendering
# ---------------------------------------------------------------------------

def link(record: dict) -> str:
    """The download cell: a link labelled with its Hugging Face repo (or its
    host), or a plain note when target.json records no trustworthy URL."""
    url = record["url"]
    if not url:
        return "**none recorded**"
    rest = url.split("://", 1)[-1]
    host, _, path = rest.partition("/")
    bits = [b for b in path.split("/") if b]
    label = "/".join(bits[:2]) if host.endswith("huggingface.co") and len(bits) >= 2 else host
    return f"[{label}]({url})"


def tier_cell(record: dict) -> str:
    """required / accelerator / optional, and what an optional file turns on."""
    tier = record["tier"]
    if tier != "optional":
        return tier
    feature = next((u["feature"] for u in record["uses"]
                    if u["tier"] == "optional" and u["feature"]), "")
    return f"optional — {feature}" if feature else "optional"


def targets_cell(record: dict, only: tuple[str, ...] | None = None) -> str:
    """The targets that load this file, each annotated when it wants the file
    at a weaker tier than the row's. `only` narrows it to those targets (the
    minimum-set tables, where the rest are beside the point)."""
    bits = []
    for u in record["uses"]:
        if only and u["target"] not in only:
            continue
        note = ""
        if u["tier"] != record["tier"]:
            note = (f" ({u['tier']}: {u['feature']})"
                    if u["tier"] == "optional" and u["feature"] else f" ({u['tier']})")
        bits.append(f"`{u['target']}`{note}")
    return ", ".join(bits)


def row(record: dict, with_size: bool, only: tuple[str, ...] | None = None) -> str:
    cells = [f"`{record['file']}`", f"`models/{record['folder']}/`"]
    if with_size:
        cells.append(record["size"] or "—")
    cells += [tier_cell(record), targets_cell(record, only), link(record)]
    return "| " + " | ".join(cells) + " |"


def table(records: list[dict], with_size: bool,
          only: tuple[str, ...] | None = None) -> list[str]:
    head = ["File", "ComfyUI folder"] + (["Size"] if with_size else []) \
        + ["Tier", "Targets", "Download"]
    return ["| " + " | ".join(head) + " |",
            "|" + "|".join(["---"] * len(head)) + "|"] \
        + [row(r, with_size, only) for r in records]


def block() -> str:
    """The generated section, between (but not including) the markers."""
    records = collect()
    with_size = any(r["size"] for r in records)
    minimum = [r for r in records if any(u["target"] in MINIMUM for u in r["uses"])]
    need = [r for r in minimum if r["tier"] == "required"]
    lines: list[str] = []

    lines += [
        "### The minimum set",
        "",
        f"The two default targets — `{TG.DEFAULT_VIDEO_TARGET}` (the video model every shot "
        f"renders on unless the script says otherwise) and `{TG.DEFAULT_IMAGE_TARGET}` (the "
        f"image model that draws the character sheets, props and location plates) — need "
        f"{len(need)} required files:",
        "",
    ]
    lines += table(need, with_size, MINIMUM)
    accel = [r for r in minimum if r["tier"] != "required"]
    if accel:
        lines += ["", "Plus, for those two targets:", ""]
        lines += table(accel, with_size, MINIMUM)
    lines += [
        "",
        "An **accelerator** is a turbo/distilled LoRA or checkpoint: without it the pass "
        "still renders, on its slower `base` preset (more steps, no LoRA), and the take's "
        "sidecar says so. A **required** file missing skips the shot. An **optional** file "
        "only switches off the feature named beside it.",
        "",
        "### Everything, by model family",
        "",
        "Every file any target names. `python h3.py targets` tells you which of these your "
        "ComfyUI is actually missing — you only need the families of the targets you use.",
        "",
    ]
    for family, records_ in families(records):
        label = modelid.family_label(family) or family
        lines += [f"**{label}** (`{family}`)", ""]
        lines += table(records_, with_size)
        lines += [""]

    nourl = [r for r in records if not r["url"]]
    if nourl:
        lines += ["#### Files with no recorded download URL", "",
                  "h3pipe only records a URL it can trace to a ComfyUI template, a saved "
                  "workflow or ComfyUI-Manager's model list, so these are listed without "
                  "one rather than with a guess:", ""]
        for r in sorted(nourl, key=lambda r: r["file"]):
            lines += [f"- `{r['file']}` → `models/{r['folder']}/` — {r['source']}"]
        lines += [""]
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# the file
# ---------------------------------------------------------------------------

def splice(text: str, body: str) -> str:
    """`text` with everything between the markers replaced by `body`."""
    start, end = text.find(BEGIN), text.find(END)
    if start < 0 or end < 0 or end < start:
        raise SystemExit(f"  !! {os.path.basename(INSTALL)} has no "
                         f"{BEGIN} / {END} markers")
    return text[:start] + BEGIN + "\n\n" + body + "\n\n" + text[end:]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[1],
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="don't write: exit 1 if INSTALL.md is out of date")
    ap.add_argument("--stdout", action="store_true", help="print the block and stop")
    args = ap.parse_args()
    body = block()
    if args.stdout:
        sys.stdout.write(body + "\n")
        return 0
    with open(INSTALL, encoding="utf-8") as fh:
        text = fh.read()
    updated = splice(text, body)
    if args.check:
        if updated != text:
            print("  !! INSTALL.md's model list is out of date — run "
                  "`python tools/make_models_md.py`")
            return 1
        print("  INSTALL.md's model list is up to date")
        return 0
    if updated == text:
        print("  INSTALL.md's model list is already up to date")
        return 0
    with open(INSTALL, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(updated)
    print(f"  -> {INSTALL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
